// Opcodes are 6 bytes long for alignment.
#define INSTR_PUT 0
#define INSTR_CLS 1
#define INSTR_ST 2
#define INSTR_MST 3
#define INSTR_LD 4
#define INSTR_MLD 5
#define INSTR_SWP 6
#define INSTR_ADD 7
#define INSTR_SUB 8
#define INSTR_NEG 9
#define INSTR_MUL 10
#define INSTR_DIV 11
#define INSTR_MOD 12
#define INSTR_LEN 13
#define INSTR_INS 14
#define INSTR_CAT 15
#define INSTR_SBS 16
#define INSTR_CMP 17
#define INSTR_CASI 18
#define INSTR_IASC 19
#define INSTR_STOI 20
#define INSTR_ITOS 21
#define INSTR_JMP 22
#define INSTR_JB 23
#define INSTR_JE 24
#define INSTR_JA 25
#define INSTR_NOP 26
#define INSTR_TYPE 27
#define INSTR_RUN 28
